title: Yuchen Song's Blog
SEOTitle: 宋雨晨的博客 | SYC's Blog
header-img: '/img/postbackdesk.jpg'
email: yuchen.song@connect.polyu.hk
description: "Every failure is leading towards success."
keyword: "Yuchen Song, SUSTech, PolyU, Biomedical Imaging, Adaptive opctics, Wavefront Shaping, Biophotonics"
url: "yuchen.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/yuchensong960426/yuchen.github.io" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Grasp all, lose all！"
sidebar-avatar: '/img/Yuchen.jpg'      # use absolute URL, seeing it's used in both `/` and `/about/`

# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "你的名字" # 你的名字
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : disqus # 使用 disqus 评论模块，读者翻墙才能看见
  duoshuo :
    short_name :  # 填写你的 disqus id
  disqus :
      short_name :  # 填写你的 disqus id

# Analytics and webmaster tools stuff goes here
google_analytics:  # 填写你  google_analytics id
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
