title: Yuchen Song's Blog
SEOTitle: 宋雨晨的博客 | SYC's Blog
header-img: /img/post-bg-desk.jpg
email: yuchen.song@connect.polyu.hk
description: "Every failure is leading towards success."
keyword: "Yuchen Song, SUSTech, PolyU, Biomedical Imaging, Adaptive opctics, Wavefront Shaping, Biophotonics"
url: "yuchensong960426.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/yuchensong960426/yuchensong960426.github.io" # you code repository
